let cobrosCargando=false, cobrosTimer;
function preferenciaCobros(key,fallback){try{return localStorage.getItem(key)??fallback}catch{return fallback}}
function guardarPreferenciaCobros(key,value){try{localStorage.setItem(key,String(value))}catch{}}
function iniciarCobros(){if(obtenerUsuarioActivo()?.rol!=='admin')return;
 const select=document.querySelector('#frecuenciaCobros');const value=preferenciaCobros('flamitasCobrosHoras','24');select.value=['0','12','24','48'].includes(value)?value:'24';
 select.onchange=()=>{guardarPreferenciaCobros('flamitasCobrosHoras',select.value);guardarPreferenciaCobros('flamitasCobrosUltimo',Date.now());document.querySelector('#avisoSeguimientoCobros')?.remove();};
 document.querySelector('#actualizarCobros').onclick=()=>cargarCobros();
 clearInterval(cobrosTimer);cargarCobros();cobrosTimer=setInterval(()=>{if(!document.hidden)cargarCobros()},60000);
}
async function cargarCobros(){if(cobrosCargando)return;cobrosCargando=true;try{
 const data=await api('/api/admin/receivables');const money=n=>n===null?'Configurar saldo':new Intl.NumberFormat('es-UY',{style:'currency',currency:'UYU'}).format(n);
 document.querySelector('#resumenCobros').innerHTML='<article class="dashboard-card"><span>Dinero por cobrar</span><strong>'+money(data.toCollect)+'</strong></article><article class="dashboard-card"><span>Dinero en caja registrado</span><strong>'+money(data.cash)+'</strong></article>';
 document.querySelector('#mensajeCobros').textContent=data.pending.length+' pedidos pendientes de cobro.'+(data.unregisteredPaid?' Hay '+data.unregisteredPaid+' pedidos pagados anteriores o sin movimiento de caja. Revisalos en Gastos y saldo para evitar omisiones o duplicados.':'');
 const lista=document.querySelector('#listaCobros');lista.replaceChildren();for(const p of data.pending){const card=document.createElement('article');card.className='finanzas-item';card.innerHTML='<strong>Pedido #'+p.id+' · '+escaparHTML(p.cliente)+'</strong><p>'+escaparHTML(p.date)+' · '+money(p.total)+' · '+escaparHTML(p.medio)+'</p>';
 const status=document.createElement('p');status.setAttribute('role','status');const b=document.createElement('button');b.type='button';b.textContent='Confirmar pago recibido';b.onclick=async()=>{if(!confirm('¿Verificaste que recibiste '+money(p.total)+' del pedido #'+p.id+'? Se registrará un cobro en caja con fecha de hoy.'))return;b.disabled=true;try{await api('/api/admin/orders/'+p.id+'/payment','POST',{total:p.total});await cargarDatosServidor();mostrarDashboardAdmin();mostrarPedidosAdmin();await leerFinanzas(false);if(typeof cargarComprobantes==='function')await cargarComprobantes(false);await cargarCobros();}catch(e){status.textContent=e.message+' Actualizá antes de repetir.';b.disabled=false;}};card.append(b,status);lista.append(card);}
 let indicador=document.querySelector('#indicadorCobros');if(!indicador){indicador=document.createElement('button');indicador.id='indicadorCobros';indicador.type='button';indicador.className='aviso-comprobantes';document.querySelector('#seccionDashboard').prepend(indicador);indicador.onclick=()=>mostrarSeccionAdmin('cobros');}indicador.textContent='Por cobrar: '+money(data.toCollect)+' · '+data.pending.length+' pedidos';
 const hours=Number(document.querySelector('#frecuenciaCobros').value);const last=Number(preferenciaCobros('flamitasCobrosUltimo','0'));
 if(!data.pending.length||!hours)document.querySelector('#avisoSeguimientoCobros')?.remove();
 else if(Date.now()-last>=hours*3600000&&!document.querySelector('#avisoSeguimientoCobros')){const aviso=document.createElement('div');aviso.id='avisoSeguimientoCobros';aviso.className='panel-comprobantes';aviso.setAttribute('role','status');aviso.textContent='Seguimiento de pagos: '+data.pending.length+' pedidos por cobrar. ';const ver=document.createElement('button');ver.type='button';ver.textContent='Revisar pendientes';ver.onclick=()=>{mostrarSeccionAdmin('cobros');guardarPreferenciaCobros('flamitasCobrosUltimo',Date.now());aviso.remove();};const luego=document.createElement('button');luego.type='button';luego.textContent='Recordarme más tarde';luego.onclick=()=>{guardarPreferenciaCobros('flamitasCobrosUltimo',Date.now());aviso.remove();};aviso.append(ver,luego);document.querySelector('.admin-panel').before(aviso);}
 }catch(e){document.querySelector('#mensajeCobros').textContent='No pudimos actualizar los cobros. '+e.message;}finally{cobrosCargando=false;}}
