import {test} from 'node:test';import assert from 'node:assert/strict';
import {emptyFinance,validateFinance,financeSummary} from '../server/finance.js';
import {PGlite} from '@electric-sql/pglite';import {createApp,initialize} from '../server/app.js';
const sample=()=>({start:'2026-01-01',opening:1000,expenses:[{id:'expense-1',description:'Cera',category:'Insumos',supplier:'',date:'2026-01-05',total:300,installments:[{amount:100,due:'2026-01-05',paidAt:'2026-01-05'},{amount:100,due:'2026-02-05',paidAt:null},{amount:100,due:'2026-03-05',paidAt:null}]}],movements:[{id:'movement-1',type:'cobro',description:'Venta',date:'2026-01-06',amount:500,orderId:null},{id:'movement-2',type:'aporte',description:'Aporte',date:'2026-01-06',amount:100},{id:'movement-3',type:'retiro',description:'Retiro',date:'2026-01-06',amount:50},{id:'movement-4',type:'devolucion',description:'Devolución',date:'2026-01-06',amount:25}]});
test('Finanzas: caja, cuotas, aportes y devoluciones sin duplicar el costo total',()=>{const d=sample();validateFinance(d);const s=financeSummary(d,'2026-02-10');assert.equal(s.paid,100);assert.equal(s.collected,500);assert.equal(s.result,375);assert.equal(s.balance,1425);assert.equal(s.pending,200);assert.equal(s.overdue,100);assert.equal(s.next30,200);assert.equal(s.afterCommitments,1225);d.expenses[0].installments[1].paidAt='2026-02-10';const n=financeSummary(d,'2026-02-10');assert.equal(n.balance,1325);assert.equal(n.pending,100);assert.equal(n.afterCommitments,1225);});
test('Finanzas: saldo sin configurar y cortes históricos no inventan fondos',()=>{assert.equal(financeSummary(emptyFinance(),'2026-01-01').balance,null);const d=sample();d.expenses[0].installments[1].paidAt='2026-02-20';assert.equal(financeSummary(d,'2026-02-10').pending,200);d.start='2026-01-07';assert.equal(financeSummary(d,'2026-02-10').balance,1000);assert.equal(financeSummary(d,'2025-12-31').balance,null);});
test('Finanzas: rechaza fechas, importes, cuotas incoherentes y cobros duplicados',()=>{for(const change of [d=>d.expenses[0].installments[0].amount=99,d=>d.expenses[0].date='2026-02-30',d=>d.movements[0].amount=-1,d=>d.expenses[0].installments[0].paidAt='2099-01-01',d=>{d.movements[0].orderId=1;d.movements.push({...d.movements[0],id:'duplicate-1'})}]){const d=sample();change(d);assert.throws(()=>validateFinance(d));}});
test('Finanzas API: privada, persistente y protegida contra cambios simultáneos',async t=>{
 const pg=new PGlite();let tail=Promise.resolve();async function lock(){const prev=tail;let release;tail=new Promise(r=>release=r);await prev;return release;}
 const query=(s,a)=>a?pg.query(s,a):s.includes('CREATE TABLE')?pg.exec(s):pg.query(s);const db={query:async(s,a)=>{const r=await lock();try{return await query(s,a)}finally{r()}},connect:async()=>{const release=await lock();return {query,release}}};
 await initialize(db,{ADMIN_EMAIL:'admin@example.com',ADMIN_PASSWORD:'test-admin-password-123'});const server=createApp(db).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(async()=>{await new Promise(r=>server.close(r));await pg.close()});
 const base='http://127.0.0.1:'+server.address().port;async function request(url,method='GET',body,cookie=''){const r=await fetch(base+url,{method,headers:{'X-Flamitas':'1','Content-Type':'application/json',Cookie:cookie},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}
 assert.equal((await request('/api/admin/finance')).status,403);
 const admin=(await request('/api/login','POST',{email:'admin@example.com',password:'test-admin-password-123'})).cookie;
 const user=(await request('/api/register','POST',{nombre:'Ana',email:'ana@example.com',password:'test-customer-password'})).cookie;assert.equal((await request('/api/admin/finance','GET',null,user)).status,403);
 const initial=await request('/api/admin/finance?date=2026-02-10','GET',null,admin);assert.equal(initial.data.summary.balance,null);
 const body={version:initial.data.version,data:sample()};assert.equal((await request('/api/admin/finance','PUT',body,user)).status,403);assert.equal((await request('/api/admin/finance','PUT',body,admin)).status,200);assert.equal((await request('/api/admin/finance','PUT',body,admin)).status,409);
 const saved=await request('/api/admin/finance?date=2026-02-10','GET',null,admin);assert.equal(saved.data.summary.balance,1425);assert.deepEqual(saved.data.data,body.data);
 const bad=structuredClone(saved.data.data);bad.movements[0].orderId=999;assert.equal((await request('/api/admin/finance','PUT',{version:saved.data.version,data:bad},admin)).status,400);

 const created=await request('/api/orders','POST',{requestId:'collect-test',productos:[{id:1,cantidad:1}],entrega:{metodo:'Retiro'},pago:{medio:'Transferencia bancaria'}},user);assert.equal(created.status,201);const order=created.data;
 assert.equal((await request('/api/admin/receivables','GET',null,user)).status,403);
 let receivables=await request('/api/admin/receivables','GET',null,admin);assert.ok(receivables.data.pending.some(p=>p.id===order.id));assert.equal(receivables.data.toCollect,order.total);
 const route='/api/admin/orders/'+order.id+'/payment';assert.equal((await request(route,'POST',{total:order.total},user)).status,403);assert.equal((await request(route,'POST',{total:1},admin)).status,409);
 assert.equal((await request(route,'POST',{total:order.total},admin)).status,200);assert.equal((await request(route,'POST',{total:order.total},admin)).status,200);
 let cash=(await request('/api/admin/finance','GET',null,admin)).data;assert.equal(cash.data.movements.filter(m=>m.orderId===order.id).length,1);assert.equal(cash.data.movements.find(m=>m.orderId===order.id).amount,order.total);
 receivables=await request('/api/admin/receivables','GET',null,admin);assert.equal(receivables.data.toCollect,0);
 let state=(await request('/api/bootstrap','GET',null,admin)).data;state.pedidos.find(p=>p.id===order.id).pago.estado='Pendiente';assert.equal((await request('/api/admin/state','PUT',{version:state.version,data:{pedidos:state.pedidos}},admin)).status,200);
 cash=(await request('/api/admin/finance','GET',null,admin)).data;assert.equal(cash.data.movements.filter(m=>m.orderId===order.id).length,0);
 state=(await request('/api/bootstrap','GET',null,admin)).data;state.pedidos.find(p=>p.id===order.id).pago.estado='Pagado';assert.equal((await request('/api/admin/state','PUT',{version:state.version,data:{pedidos:state.pedidos}},admin)).status,200);
 cash=(await request('/api/admin/finance','GET',null,admin)).data;assert.equal(cash.data.movements.filter(m=>m.orderId===order.id).length,1);
 state=(await request('/api/bootstrap','GET',null,admin)).data;state.pedidos.find(p=>p.id===order.id).estado='Cancelado';assert.equal((await request('/api/admin/state','PUT',{version:state.version,data:{pedidos:state.pedidos}},admin)).status,200);
 cash=(await request('/api/admin/finance','GET',null,admin)).data;assert.equal(cash.data.movements.filter(m=>m.orderId===order.id).length,1);assert.equal((await request('/api/admin/receivables','GET',null,admin)).data.pending.length,0);
 assert.equal((await request('/api/bootstrap','GET',null,user)).data.finance,undefined);
});
